[tool.poetry]
name = "python-awair"
version = "0.0.5"
description = "asyncio client for the Awair GraphQL API"
authors = ["Andrew Hayworth <ahayworth@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/ahayworth/python_awair"
repository = "https://github.com/ahayworth/python_awair"
keywords = ["awair", "getawair", "api", "async", "asyncio"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: AsyncIO",
    "Intended Audience :: Developers",
    "Topic :: Home Automation",
    "Topic :: Software Development :: Libraries",
    "Typing :: Typed"
]

[tool.poetry.dependencies]
python = "^3.6"
aiohttp = "~3.6.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^19.10b0"
python-language-server = "^0.31.9"
pyls-black = "^0.4.4"
flake8 = "^3.7.9"
isort = "^4.3.21"
pyls-isort = "^0.1.1"
tox = "^3.14.6"
aioresponses = "^0.6.3"
pylint = "^2.4.4"
pytest-aiohttp = "^0.3.0"
pydocstyle = "^5.0.2"

[tool.poetry.urls]
"Say Thanks" = "https://saythanks.io/to/ahayworth@gmail.com"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py36, py37, py38
isolated_build = True
skipsdist = True
skip_missing_interpreters = True

[gh-actions]
python =
  3.6: py36
  3.7: py37
  3.8: py38

[testenv]
whitelist_externals = poetry
commands = poetry run pytest {posargs}

[testenv:lint]
whitelist_externals = poetry
commands = poetry run black . --check
"""

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
